### ISSUE TITLE
NHL.TV streams not working anymore

### ISSUE THREAD

**Issue by tekbec** [tekbec/plugin.video.nhl66#10]
NHL.TV live streams won't start or start at the beginning of the stream instead of live and no way to forward.

**Comment by theboyk** [comment]
Could this be related to the issue I'm seeing? I can't even access Live Events or Game Replays at all; selecting either of those from the main menu just gives me an error alert ("HTTPError")?

**Comment by tekbec** [comment]
I would need more context to know if this is related. Do you have a log file or error description?

**Comment by theboyk** [comment]
> I would need more context to know if this is related. Do you have a log file or error description?

It seems to be back to normal this am. Not sure if it was a temporary issue on my end, or server-side, but it's all back to normal for me now. Thanks.

**Comment by tekbec** [comment]
Excellent, I'll close this issue, but feel free to reopen it if it comes back.
