### ISSUE TITLE
Pour les québécois

### ISSUE THREAD

**Issue by JulioQc** [tekbec/plugin.video.nhl66#3]
Si je suis au Québec ya tu moyen de jouer un stream ou faut absolument avoir un proxy? 
Tout semble venir de ESPN+ ou NHL.TV (RDS shows as NHL.TV)

**Comment by tekbec** [comment]
Salut! Au Canada ça prend absolument un proxy. Pour les streams ESPN, un proxy américain est requis et pour NHL.TV, c’est un proxy dans un pays d’Europe ou d’Asie qui est requis.
