### ISSUE TITLE
No way to enter username/password for custom Proxies

### ISSUE THREAD

**Issue by theboyk** [tekbec/plugin.video.nhl66#4]
Any chance we could get a way to enter credentials for custom (non-TorGuard) proxies? My proxies (via PIA) also require a username/password, but don't see a way to pass those with the proxy itself?

**Comment by tekbec** [comment]
Yes, in the proxy window, select Custom and enter your credentials in the following format:

`https://username:password@your.proxyhostname.com:8080`

SOCKS5 proxies should also work by replacing https:// with socks://

**Comment by Sumoallstar** [comment]
Regarding SOCKS5 proxies, I found I needed to replace "https://" with "socks5://" for my provider (ipVansish). Using only "socks://" resulted in  an "unknown socks version" error (or wording similar to that)

**Comment by theboyk** [comment]
Ah, the "socks5://" did the trick! Thanks @Sumoallstar & @tekbec, for everything!
