### ISSUE TITLE
Can't install NHL66

### ISSUE THREAD

**Issue by angernizer** [tekbec/plugin.video.nhl66#9]
Hi,

I tried to do an installation on a new device but i always get the “Failed to install a dependency” error. Everything works fine on my older device.

Thanks!

**Comment by tekbec** [comment]
What device are you using and can you upload your Kodi Debug Log?

**Comment by angernizer** [comment]
It is a Chromecast Google TV. I achieved to install the dependency from the Kodi repository. The error in the log was "kodi failed ssl connect error 35"

Thanks

**Comment by tekbec** [comment]
Glad you found a way to solve this. Marking it as solved.
